# Generated by Django 5.2.12 on 2026-04-04 12:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('useful_life_years', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_account', to='core.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_payment_account', to='core.account')),
            ],
        ),
    ]
