# Generated by Django 5.2.12 on 2026-04-02 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='core.invoice'),
        ),
    ]
