# Generated by Django 5.2.12 on 2026-04-05 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payment_journal_entry_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_entry', to='core.journalentry'),
        ),
    ]
