# Generated by Django 5.2.12 on 2026-04-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_journalentry_is_cancelled_alter_journalentry_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
