# Generated by Django 5.2.12 on 2026-04-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_payment_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank')], default='cash', max_length=20),
        ),
    ]
